### ISSUE TITLE
cannot build with ghc-8.6.3: Not in scope: type constructor or class ‘L.MetadataNode’ 

### ISSUE THREAD

**Issue by jwaldmann** [AccelerateHS/accelerate-fft#8]
Yes I know I'm on thin ice with `allow-newer`. But sometimes it does the job. Here it doesn't:
```
cabal install  accelerate-fft --flags="-llvm-ptx" --allow-newer 
...
Building library for accelerate-llvm-1.2.0.0..
...
[47 of 60] Compiling Data.Array.Accelerate.LLVM.CodeGen.Downcast ( src/Data/Array/Accelerate/LLVM/CodeGen/Downcast.hs
, dist/build/Data/Array/Accelerate/LLVM/CodeGen/Downcast.o )                                                        
                                                                              
src/Data/Array/Accelerate/LLVM/CodeGen/Downcast.hs:378:32: error:                                                    
    Not in scope: type constructor or class ‘L.MetadataNode’                       
    Perhaps you meant one of these:                                                                                 
      ‘L.MetadataNodeID’ (imported from LLVM.AST.Operand),                                                           
      ‘L.Metadata’ (imported from LLVM.AST.Operand)                 
...
```
and many similar errors. 

I guess it's got nothing to do with ghc-8.6. per se, but with the version of `llvm-hs[-pure]` that is implied.
I found that `MetadataNode` was present in `llvm-hs-pure` 6.0.0, but vanished in 6.1.0, cf.
https://hackage.haskell.org/package/llvm-hs-pure-6.1.0/changelog

**Comment by tmcdonell** [comment]
The GitHub versions should work with 8.6 now, if you are able to upgrade your code to the (unreleased) 1.3.* series.

**Comment by tmcdonell** [comment]
I have (finally) made some patch releases for ghc-8.6, it should be all good now. Sorry for the delay!
